export const SHOW_AVATAR_MENU : string = "showAvatarMenu"
export const ZONE_STATUS : string = "zoneStatus"
export const SET_AUTH_ERROR : string = "setAuthError"
export const SET_AUTH_ACCESS : string = "setAuthACCESS"
export const PasswordModal = "PASSWORD_MODAL"
export const ZoneModal = "ZONE_MODAL"