export default interface Request{
    RID : number,
    RCount : number,
    RAcceptCount : number,
    RTime : Date,
    RAcceptTime : Date,
    RDetails : string,
    EZID : number,
    HTID : number,
    SID : number,
    RTID : number,
    STUID : number,
    ESID : number,
    EFullname : string,
    ZCode : string,
    SName : string,
    HTName : string,
    HName : string,
    RTName : string,
    RTimeGet : string,
    RAcceptTimeGet : string
}